@testset "1039.minimum-score-triangulation-of-polygon.jl" begin
    @test min_score_triangulation([1, 3, 1, 4, 1, 5]) == 13
    @test min_score_triangulation([3, 7, 4, 5]) == 144
    @test min_score_triangulation([1, 2, 3]) == 6
    @test min_score_triangulation([
        1,
        1,
        9,
        2,
        5,
        2,
        2,
        10,
        9,
        4,
        8,
        2,
        8,
        6,
        6,
        8,
        7,
        5,
        5,
        5,
        10,
        3,
        10,
        1,
        4,
        1,
        4,
        2,
        3,
        8,
        6,
        1,
        5,
        5,
        7,
        6,
        4,
        5,
        8,
        2,
        1,
        8,
        3,
        8,
        5,
        5,
        2,
        3,
        3,
        1,
    ]) == 1078
end
