@testset "894.all-possible-full-binary-trees.jl" begin
    @test all_possible_fbt(7) == [TreeNode{Int64}(0, TreeNode{Int64}(0, nothing, nothing),
                           TreeNode{Int64}(0, TreeNode{Int64}(0, nothing, nothing),
                                           TreeNode{Int64}(0,
                                                           TreeNode{Int64}(0, nothing,
                                                                           nothing),
                                                           TreeNode{Int64}(0, nothing,
                                                                           nothing)))),
           TreeNode{Int64}(0, TreeNode{Int64}(0, nothing, nothing),
                           TreeNode{Int64}(0,
                                           TreeNode{Int64}(0,
                                                           TreeNode{Int64}(0, nothing,
                                                                           nothing),
                                                           TreeNode{Int64}(0, nothing,
                                                                           nothing)),
                                           TreeNode{Int64}(0, nothing, nothing))),
           TreeNode{Int64}(0,
                           TreeNode{Int64}(0, TreeNode{Int64}(0, nothing, nothing),
                                           TreeNode{Int64}(0, nothing, nothing)),
                           TreeNode{Int64}(0, TreeNode{Int64}(0, nothing, nothing),
                                           TreeNode{Int64}(0, nothing, nothing))),
           TreeNode{Int64}(0,
                           TreeNode{Int64}(0, TreeNode{Int64}(0, nothing, nothing),
                                           TreeNode{Int64}(0,
                                                           TreeNode{Int64}(0, nothing,
                                                                           nothing),
                                                           TreeNode{Int64}(0, nothing,
                                                                           nothing))),
                           TreeNode{Int64}(0, nothing, nothing)),
           TreeNode{Int64}(0,
                           TreeNode{Int64}(0,
                                           TreeNode{Int64}(0,
                                                           TreeNode{Int64}(0, nothing,
                                                                           nothing),
                                                           TreeNode{Int64}(0, nothing,
                                                                           nothing)),
                                           TreeNode{Int64}(0, nothing, nothing)),
                           TreeNode{Int64}(0, nothing, nothing))]
    @test all_possible_fbt(3) == [TreeNode{Int64}(0, TreeNode{Int64}(0, nothing, nothing),
                           TreeNode{Int64}(0, nothing, nothing))]
    @test all_possible_fbt(2) == TreeNode{Int}[]
end